[package]
name = "drop-transfer"
version = "1.0.0"
edition = "2021"
resolver = "2"

[[example]]
name = "udrop"

[dev-dependencies]
clap = { version = "3.2", features = ["cargo"] }
slog-async = "2.7.0"
slog-term = "2.9"

[dependencies]
slog = { workspace = true }
lazy_static = "1.4.0"
drop-config = { version = "1.0.0", path = "../drop-config" }
drop-analytics = { version = "1.0.0", path = "../drop-analytics" }
uuid = { version = "1.2", features = ["v4"] }
futures = "0.3"
futures-util = "0.3"
thiserror = "1.0"
tokio = { workspace = true }
tokio-util = "0.7.3"
walkdir = "2"
libc = "0.2"
warp = { version = "0.3.3", default-features = false, features = ["websocket"] }
serde = { version = "1.0.152", features = ["derive"] }
anyhow = "1.0.68"
serde_json = "1.0.91"
tokio-tungstenite = "0.17.2"
infer = "0.12.0"
hyper = "0.14.24"
strum = { version = "0.24.1", features = ["derive"] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9"
