[package]
name = "norddrop"
version = "0.1.0"
authors = ["Lukas Pukenis"]
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
uuid = { version = "1.2", features = ["serde", "v4"] }
base64 = "0.13.0"
futures = "0.3"
lazy_static = "1.4.0"
libc = "0.2.99"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = { workspace = true }
thiserror = "1.0"
tokio = { workspace = true }

drop-transfer = { version = "1.0", path = "../drop-transfer" }
drop-config = { version = "1.0", path = "../drop-config" }
drop-analytics = { version = "1.0", path = "../drop-analytics" }

[dev-dependencies]
mockall = "0.10.2"
ntest = "0.7"
pretty_assertions = "0.7.2"

[build-dependencies]
cc = "1.0.74"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["netioapi", "ntdef", "winerror", "ws2def"] }
